  version: "3.8"

  services:
    dynamodb-local:
      image: amazon/dynamodb-local:latest
      container_name: dynamodb-local
      ports:
        - "8000:8000"
      command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
      volumes:
        - ./dynamodb-data:/data

    sqs-local:
      image: softwaremill/elasticmq-native:latest
      container_name: sqs-local
      ports:
        - "9324:9324"
        - "9325:9325"