spring:
  profiles:
    active: local

server:
  port: 8080

aws:
  region: sa-east-1
  credentials:
    access-key: local
    secret-key: local
  dynamodb:
    endpoint: http://localhost:8000
  sqs:
    endpoint: http://localhost:9324
    queues:
      sqs-sistema-votacao-resultados: sqs-sistema-votacao-resultados

logging:
  level:
    root: INFO
    br.com.sicredi.sistemavotacao: DEBUG
    org.springframework.web: INFO
    org.springframework.data: INFO
    software.amazon.awssdk: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    dynamodb:
      enabled: true
    sqs:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs # Caminho para o JSON da OpenAPI
  swagger-ui:
    path: /swagger-ui.html # Caminho para o Swagger UI

app:
  cpf-validation:
    url: https://user-info.herokuapp.com/users
  voting:
    default-session-duration: PT1M  # 1 minuto em formato ISO-8601